version: "3.7"

services:
  redis:
    image: redis:7.4-alpine
    restart: always
    volumes:
      - ${APP_DATA_DIR}/data/redis:/data

  db:
    # Using the standard PostGIS image for maximum compatibility
    image: postgis/postgis:17-3.5-alpine
    shm_size: 1G
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dawarich_production
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/postgresql/data

  app:
    image: freikin/dawarich:latest
    restart: always
    entrypoint: web-entrypoint.sh
    command: ['bin/rails', 'server', '-p', '3000', '-b', '0.0.0.0']
    volumes:
      - ${APP_DATA_DIR}/data/public:/var/app/public
      - ${APP_DATA_DIR}/data/watched:/var/app/tmp/imports/watched
      - ${APP_DATA_DIR}/data/storage:/var/app/storage
    environment:
      RAILS_ENV: production
      REDIS_URL: redis://redis:6379
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_production
      APPLICATION_HOSTS: "*"
      TIME_ZONE: UTC
      APPLICATION_PROTOCOL: http
      # Umbrel provides this automatically
      SECRET_KEY_BASE: ${APP_PASSWORD}
      RAILS_LOG_TO_STDOUT: "true"
      SELF_HOSTED: "true"
      STORE_GEODATA: "true"

  sidekiq:
    image: freikin/dawarich:latest
    restart: always
    entrypoint: sidekiq-entrypoint.sh
    command: ['sidekiq']
    volumes:
      - ${APP_DATA_DIR}/data/public:/var/app/public
      - ${APP_DATA_DIR}/data/watched:/var/app/tmp/imports/watched
      - ${APP_DATA_DIR}/data/storage:/var/app/storage
    environment:
      RAILS_ENV: production
      REDIS_URL: redis://redis:6379
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_production
      BACKGROUND_PROCESSING_CONCURRENCY: 5
      SECRET_KEY_BASE: ${APP_PASSWORD}
