services:
  # Main Application
  web:
    image: freikin/dawarich:latest
    container_name: moxy_dawarich_app
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - dawarich_public:/var/app/public
      - dawarich_watched:/var/app/tmp/imports/watched
      - dawarich_storage:/var/app/storage
      - dawarich_db_data:/dawarich_db_data
    environment:
      RAILS_ENV: production
      REDIS_URL: redis://dawarich_redis:6379
      DATABASE_HOST: dawarich_db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_production
      APPLICATION_HOSTS: "*"
      TIME_ZONE: Europe/London
      APPLICATION_PROTOCOL: http
      SECRET_KEY_BASE: "CHANGE_ME_TO_A_LONG_RANDOM_STRING"
      RAILS_LOG_TO_STDOUT: "true"
      SELF_HOSTED: "true"
      STORE_GEODATA: "true"
      # SMTP Settings
      SMTP_SERVER: "smtp.gmail.com"
      SMTP_PORT: 587
      SMTP_USERNAME: "your-email@gmail.com"
      SMTP_PASSWORD: "your-app-specific-password"
      SMTP_FROM: "your-email@gmail.com"
      SMTP_DOMAIN: "gmail.com"
      SMTP_STARTTLS: "true"
      SMTP_AUTHENTICATION: "plain"
    networks:
      default:
    depends_on:
      dawarich_db:
        condition: service_healthy
      dawarich_redis:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 10s
      timeout: 10s
      retries: 5    

  # Background Worker
  sidekiq:
    image: freikin/dawarich:latest
    container_name: dawarich_sidekiq
    restart: on-failure
    entrypoint: sidekiq-entrypoint.sh
    command: ['sidekiq']
    volumes:
      - dawarich_public:/var/app/public
      - dawarich_watched:/var/app/tmp/imports/watched
      - dawarich_storage:/var/app/storage
    environment:
      RAILS_ENV: production
      REDIS_URL: redis://dawarich_redis:6379
      DATABASE_HOST: dawarich_db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: dawarich_production
      BACKGROUND_PROCESSING_CONCURRENCY: 5
      SECRET_KEY_BASE: "CHANGE_ME_TO_A_LONG_RANDOM_STRING"
      # SMTP Settings
      SMTP_SERVER: "smtp.gmail.com"
      SMTP_PORT: 587
      SMTP_USERNAME: "your-email@gmail.com"
      SMTP_PASSWORD: "your-app-specific-password"
      SMTP_FROM: "your-email@gmail.com"
      SMTP_DOMAIN: "gmail.com"
      SMTP_STARTTLS: "true"
      SMTP_AUTHENTICATION: "plain"
    networks:
      default:
    depends_on:
      dawarich_db:
        condition: service_healthy
      dawarich_redis:
        condition: service_healthy
      web:
        condition: service_healthy

  # Database
  dawarich_db:
    image: postgis/postgis:17-3.5-alpine
    container_name: dawarich_db
    shm_size: 1G
    volumes:
      - dawarich_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dawarich_production
    restart: always
    networks:
      default:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d dawarich_production"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  # Redis
  dawarich_redis:
    image: redis:7.4-alpine
    container_name: dawarich_redis
    command: redis-server --save 60 1 --appendonly no
    restart: always
    networks:
      default:
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5

# networks:
#  default:
#    external:
#       name: moxy-dawarich_main

volumes:
  dawarich_db_data:
  dawarich_public:
  dawarich_watched:
  dawarich_storage:
